name: Publish Chinese docs via GitHub Pages 
env:


  ACTIONTEST: 3.8.0

on:
  workflow_call:

  push:
    branches:
      # Remember to add v before the following version number unless the version is master.
      - v3.8.0

    paths:
      - 'docs-2.0-zh/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # fetch all commits/branches for gitversion

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name : prepare
        run: sh ./prepare.sh 

      - name: Git Config
        run: git config user.name ChrisChen2023 && git config user.email chris.chen@vesoft.com

          
      - name: Mike Deploy
        run: |
          python ./scripts/render_chinese_only.py
          git fetch origin gh-pages-zh --depth=1 # fix mike's CI update
          mike list
          mike deploy ${{ env.ACTIONTEST }} -b gh-pages-zh -p --rebase
          mike set-default ${{ env.ACTIONTEST }} -b gh-pages-zh -p --rebase
    